upgrading charts and adding canvas-lms chart

diff --git a/src/canvas/values.yaml b/src/canvas/values.yaml
--- a/src/canvas/values.yaml
+++ b/src/canvas/values.yaml
@@ -121,31 +121,31 @@ livenessProbe:
   timeoutSeconds: 5
   successThreshold: 1
   failureThreshold: 6
-#readinessProbe:
-#  httpGet:
-#    path: /login/canvas
-#    port: http
-#  initialDelaySeconds: 60
-#  timeoutSeconds: 90
-#  periodSeconds: 30
-#  successThreshold: 1
-#  failureThreshold: 10
 readinessProbe:
-  exec:
-    command:
-      - /bin/bash
-      - -c
-      - >
-        if passenger-status | grep -q "/usr/src/app (production)"; then
-          exit 0
-        else
-          exit 1
-        fi
-  initialDelaySeconds: 5
-  timeoutSeconds: 5
-  periodSeconds: 10
+  httpGet:
+    path: /login/canvas
+    port: http
+  initialDelaySeconds: 60
+  timeoutSeconds: 90
+  periodSeconds: 30
   successThreshold: 1
-  failureThreshold: 6
+  failureThreshold: 10
+#readinessProbe:
+#  exec:
+#    command:
+#      - /bin/bash
+#      - -c
+#      - >
+#        if passenger-status | grep -q "/usr/src/app (production)"; then
+#          exit 0
+#        else
+#          exit 1
+#        fi
+#  initialDelaySeconds: 5
+#  timeoutSeconds: 5
+#  periodSeconds: 10
+#  successThreshold: 1
+#  failureThreshold: 6
 
 delayedJobs:
   livenessProbe:
